# Numpy

In [2]:
import numpy as np

In [2]:
data1 = [1,2,3,4,5]

In [3]:
data1

[1, 2, 3, 4, 5]

In [18]:
data2 = [1,2,3,3.5,4]

In [19]:
data2

[1, 2, 3, 3.5, 4]

In [6]:
# numpy array 정의
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [8]:
arr1.shape

(5,)

In [9]:
arr2 = np.array([1,2,3,4,5])

In [10]:
arr2

array([1, 2, 3, 4, 5])

In [11]:
arr2.shape

(5,)

In [13]:
arr2.dtype

dtype('int32')

In [14]:
type(arr2)

numpy.ndarray

In [20]:
arr3= np.array(data2)

In [21]:
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [22]:
arr3.shape

(5,)

In [23]:
arr3.dtype

dtype('float64')

In [24]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
arr4.shape

(4, 3)

## 1. Array 생성 Func

    * np.zeros(n)        : 0으로 n만큼 채움
    * np.ones(n)         : 1로 n만큼 채움
    * np.arange()        : array range
    * np.full((m,m),n)   : m*m 행렬에 n으로 채움
    * np.eye(n)          : n*n 행렬에 단위행렬(우하향 1)
    * np.empty((m,m))    : 초기화하지 않은 m*m행렬 


### np.zeros()

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### np.ones()

In [30]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### np.arange()

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

### np.full()

In [38]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [51]:
# np.full(7)

TypeError: full() missing 1 required positional argument: 'fill_value'

### np.eye()

In [39]:
# 단위행렬
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.empty()

In [44]:
# 초기화 안하고 메모리값
np.empty((4,2))

array([[6.79038653e-313, 1.08111442e-309],
       [1.00047858e-309, 2.33419537e-312],
       [9.76118064e-313, 2.56761491e-312],
       [8.48798317e-313, 8.70018275e-313]])

### 같은 형태 n으로 채우기 (본뜨기)

* np.zeros_like()
* np.ones_like()
* np.empty_like()

In [46]:
a = np.arange(1,10).reshape(3,3)

In [47]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### np.zeros_like()

In [48]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### np.ones_like(a)

In [49]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### np.empty_like()


In [50]:
np.empty_like(a)

array([[-1747457568,         470,  -633275006],
       [   15169098, -1707723888,         470],
       [-1747203536,         470,  -251268321]])

## 2. Array 연산 p.57

## 3. Array Broadcast

In [54]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [55]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr1.shape

(5,)

## 4. Array indexing

In [56]:
arr1 = np.arange(10)

In [57]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr1[0]

0

In [59]:
arr1[3]

3

In [60]:
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [61]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [64]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
arr2[0,0]

1

In [66]:
arr2[0][0]

1

In [67]:
arr2[0]

array([1, 2, 3, 4])

In [68]:
arr2[2,:]

array([ 9, 10, 11, 12])

In [74]:
arr2[2,]

array([ 9, 10, 11, 12])

In [69]:
arr2[2]

array([ 9, 10, 11, 12])

In [70]:
arr2[2,3]

12

In [71]:
arr2[2][3]

12

In [72]:
arr2[:,3]

array([ 4,  8, 12])

In [31]:
arr2[,3] #열 indexing은 행을 반드시 표기

SyntaxError: invalid syntax (<ipython-input-31-e6f4110f6190>, line 1)

**********************************************************************

## 5. Array boolean (Indexing mask)

    * 논리값을 사용하여 행 추출 (R의 filter, subset)
    * 논리값(row)과 indexing(col)을 사용하여 조건에 맞는 값 0으로 처리

### 5-0. 데이터 준비

#### 실습 데이터 생성1 :변수 names 명단 생성

In [4]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])

In [83]:
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [84]:
names.shape

(8,)

In [85]:
names[0,]

'Beomwoo'

In [86]:
names[0]

'Beomwoo'

In [87]:
names[4,]

'Lee'

#### 실습 데이터 생성2 :변수 data 가상의 데이터 생성

In [22]:
# np.random.randn()
data = np.random.randn(8,4)
data

array([[ 2.72837438, -0.29775187,  0.28800626,  0.89124227],
       [-0.13550328, -0.39053428, -0.49601894, -0.78079317],
       [-0.80726942, -0.5148619 , -0.68528659, -0.95505727],
       [-0.27666841,  0.33377283,  1.34847419, -0.05325423],
       [-1.08168972, -0.82345592, -1.77985254, -0.98530172],
       [ 0.35084533,  0.82439977,  2.08019164, -0.22551055],
       [ 1.31988265, -1.77607238, -0.48136924, -0.29567129],
       [-0.83700644,  1.15320508, -0.06198135,  0.2869008 ]])

In [23]:
data.shape

(8, 4)

### 5-1. Filter 논리값을 사용하여 행 추출

#### 추출 1-1 : 변수 names_Beomwoo_mask 

    * 변수 names에서 'Beomwoo'가 있는 행 논리값

In [8]:
names =='Beomwoo'

array([ True,  True, False, False, False,  True, False,  True])

In [9]:
names_Beomwoo_mask = (names =='Beomwoo') 
# 우선순위를 표시하기 위해 () 한듯하지만 == 연산자가 =보다 우선이다.
names_Beomwoo_mask

array([ True,  True, False, False, False,  True, False,  True])

#### 추출 1-2 : 변수 names_Beomwoo_mask 논리값을 사용하여 행 추출

In [98]:
# names_Beomwoo_mask에 True가  0 1 5 7에 있으므로 data의 0 1 5 7 번째 행 추출
data[names_Beomwoo_mask,:]
# data[names =='Beomwoo',:] 같다

array([[-0.54331563, -0.32777889,  0.64537218,  0.63988793],
       [-1.1192968 , -1.09531724,  0.0063949 , -0.20249649],
       [-2.46833203, -0.4310185 ,  0.7088829 ,  1.43681365],
       [-0.96977021, -1.36506283,  0.74416561,  0.62281191]])

#### 추출 2 : 변수 저장 없이 바로 논리값으로 추출

In [99]:
data[names == 'Kim',:]

array([[ 1.96097458,  0.49007517,  0.24573623, -0.82716106]])

In [100]:
data[(names == 'Kim')|(names == 'Park'),:]

array([[ 1.96097458,  0.49007517,  0.24573623, -0.82716106],
       [-1.12232141, -0.10983702,  0.31091492, -1.04326524]])

### 5-2. 논리값과 indexing을 사용하여 조건에 맞는 값 0으로 처리

    * 0번째 열에서 0보다 작은 값이 있는 행의 2~4번째 열을 0으로 처리해보자
    
    1. 0번째 열 추출
    2. 0번째 열에서 0보다 작은 행 논리값
    3. 0번째 열에서 0보다 작은 행 추출
    4. 0번째 열에서 0보다 작은 행의 2~4번째 열 추출
    5. 0번째 열에서 0보다 작은 행의 2~4번째 열 0 대입

In [24]:
data

array([[ 2.72837438, -0.29775187,  0.28800626,  0.89124227],
       [-0.13550328, -0.39053428, -0.49601894, -0.78079317],
       [-0.80726942, -0.5148619 , -0.68528659, -0.95505727],
       [-0.27666841,  0.33377283,  1.34847419, -0.05325423],
       [-1.08168972, -0.82345592, -1.77985254, -0.98530172],
       [ 0.35084533,  0.82439977,  2.08019164, -0.22551055],
       [ 1.31988265, -1.77607238, -0.48136924, -0.29567129],
       [-0.83700644,  1.15320508, -0.06198135,  0.2869008 ]])

#### 1. 0번째 열 추출

In [25]:
data[:,0]

array([ 2.72837438, -0.13550328, -0.80726942, -0.27666841, -1.08168972,
        0.35084533,  1.31988265, -0.83700644])

#### 2. 0번째 열에서 0보다 작은 행 논리값 

In [26]:
data[:,0] < 0

array([False,  True,  True,  True,  True, False, False,  True])

#### 3. 0번째 열에서 0보다 작은 행 추출

In [27]:
data[data[:,0]<0,:] #0번째 열에 0보다 작은 값이 있는 행 추출

array([[-0.13550328, -0.39053428, -0.49601894, -0.78079317],
       [-0.80726942, -0.5148619 , -0.68528659, -0.95505727],
       [-0.27666841,  0.33377283,  1.34847419, -0.05325423],
       [-1.08168972, -0.82345592, -1.77985254, -0.98530172],
       [-0.83700644,  1.15320508, -0.06198135,  0.2869008 ]])

#### 4. 0번째 열에서 0보다 작은 행의 2~4번째 열 추출

In [28]:
data[data[:,0]<0,2:4]

array([[-0.49601894, -0.78079317],
       [-0.68528659, -0.95505727],
       [ 1.34847419, -0.05325423],
       [-1.77985254, -0.98530172],
       [-0.06198135,  0.2869008 ]])

#### 5. 0번째 열에서 0보다 작은 행의 2~4번째 열 0 대입

In [29]:
data[data[:,0]<0,2:4] = 0 
#0번째 열에서 0보다 작은 값이 있는 행의 2~4열을 0으로 처리

In [30]:
data # 해당 위치가 0인지 확인

array([[ 2.72837438, -0.29775187,  0.28800626,  0.89124227],
       [-0.13550328, -0.39053428,  0.        ,  0.        ],
       [-0.80726942, -0.5148619 ,  0.        ,  0.        ],
       [-0.27666841,  0.33377283,  0.        ,  0.        ],
       [-1.08168972, -0.82345592,  0.        ,  0.        ],
       [ 0.35084533,  0.82439977,  2.08019164, -0.22551055],
       [ 1.31988265, -1.77607238, -0.48136924, -0.29567129],
       [-0.83700644,  1.15320508,  0.        ,  0.        ]])

------------------------------------------

## 6. Numpy Func

In [3]:
arr1 = np.random.randn(5,3)

In [4]:
arr1

array([[-1.19221103, -0.78147096,  1.52427448],
       [ 0.68619103, -1.34498903, -0.55267736],
       [ 1.95189593, -0.22860076, -2.11950312],
       [ 1.3221908 , -0.12821303,  1.9311058 ],
       [ 0.03960364,  0.02657802,  0.03577257]])

In [36]:
np.abs(arr1) # 절대값

array([[2.56739153, 1.31685882, 0.50458758],
       [1.34243116, 0.05702788, 1.66894354],
       [1.97757689, 0.17526282, 0.34553999],
       [3.6667494 , 0.06136725, 0.05439832],
       [1.3467398 , 0.91840032, 0.06976475]])

In [38]:
np.sqrt(arr1) # 제곱근 (음수는 nan)

<ipython-input-38-2627eb0bb90c>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1) # 제곱근 (음수는 nan)


array([[       nan, 1.14754469, 0.71034328],
       [       nan,        nan, 1.29187598],
       [       nan, 0.41864402, 0.5878265 ],
       [       nan, 0.24772414,        nan],
       [1.16049119, 0.95833205, 0.26413017]])

In [39]:
np.square(arr1) #제곱

array([[6.59149927e+00, 1.73411716e+00, 2.54608625e-01],
       [1.80212142e+00, 3.25217912e-03, 2.78537253e+00],
       [3.91081034e+00, 3.07170556e-02, 1.19397884e-01],
       [1.34450511e+01, 3.76593922e-03, 2.95917773e-03],
       [1.81370809e+00, 8.43459148e-01, 4.86711995e-03]])

In [40]:
np.exp(arr1) #지수

array([[0.07673545, 3.73168108, 1.65630229],
       [0.26120985, 0.94456773, 5.30655865],
       [0.1384042 , 1.19155934, 1.41275258],
       [0.02555942, 1.06328933, 0.9470548 ],
       [3.84487003, 2.50527954, 1.0722559 ]])

In [41]:
np.log(arr1) #자연로그

<ipython-input-41-339f66cba926>:1: RuntimeWarning: invalid value encountered in log
  np.log(arr1) #자연로그


array([[        nan,  0.27524922, -0.68401386],
       [        nan,         nan,  0.51219081],
       [        nan, -1.74146861, -1.0626469 ],
       [        nan, -2.79087899,         nan],
       [ 0.29768671, -0.0851219 , -2.66262645]])

In [42]:
np.log10(arr1) #상용로그

<ipython-input-42-68b976e950f0>:1: RuntimeWarning: invalid value encountered in log10
  np.log10(arr1) #상용로그


array([[        nan,  0.11953922, -0.29706344],
       [        nan,         nan,  0.22244164],
       [        nan, -0.75631021, -0.46150169],
       [        nan, -1.21206335,         nan],
       [ 0.1292837 , -0.03696797, -1.15636398]])

In [43]:
np.log2(arr1) #지수로그

<ipython-input-43-d1fe40368f17>:1: RuntimeWarning: invalid value encountered in log2
  np.log2(arr1) #지수로그


array([[        nan,  0.39710069, -0.9868234 ],
       [        nan,         nan,  0.73893515],
       [        nan, -2.51240813, -1.53307541],
       [        nan, -4.02638728,         nan],
       [ 0.42947114, -0.12280495, -3.84135798]])

In [44]:
np.sign(arr1) #부호 + -> 1, - -> -1, 0 -> 0

array([[-1.,  1.,  1.],
       [-1., -1.,  1.],
       [-1.,  1.,  1.],
       [-1.,  1., -1.],
       [ 1.,  1.,  1.]])

In [131]:
np.ceil(arr1) # 소수 첫번째 반올림

array([[-0., -0.,  1.],
       [-0.,  1.,  1.],
       [ 1., -1., -0.],
       [ 1., -0., -0.],
       [-1.,  1.,  1.]])

In [132]:
np.floor(arr1)# 반내림

array([[-1., -1.,  0.],
       [-1.,  0.,  0.],
       [ 0., -2., -1.],
       [ 0., -1., -1.],
       [-2.,  0.,  0.]])

In [45]:
np.isnan(arr1) # nan유무

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [46]:
np.isnan(np.log(arr1))

<ipython-input-46-6bad7ca87a38>:1: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log(arr1))


array([[ True, False, False],
       [ True,  True, False],
       [ True, False, False],
       [ True, False,  True],
       [False, False, False]])

In [47]:
np.isinf(arr1) #무한대

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [49]:
np.cos(arr1) #코사인 (cos,cosh(쌍곡 코싸인),sin,sinh,tan,tanh)

array([[-0.83962649,  0.25121713,  0.87537393],
       [ 0.22638544,  0.99837435, -0.09798971],
       [-0.39565465,  0.98468075,  0.94089269],
       [-0.86524537,  0.99811762,  0.99852078],
       [ 0.22218657,  0.60709209,  0.99756743]])

### 2-array 적용 Func

    * np.add(A,b)
    * np.subtract(A,B)
    * np.multiply(A,B)
    * np.maximum(A,B) 각 위치값 비교후 큰값 반환
    * np.minimum(A,B) 각 위치값 비교후 작은값 반환

In [137]:
arr1

array([[-0.93418212, -0.33537537,  0.49829151],
       [-0.12366992,  0.34698235,  0.61185628],
       [ 0.1506246 , -1.21285481, -0.80655811],
       [ 0.61400856, -0.70057056, -0.0422159 ],
       [-1.9373983 ,  0.02208582,  0.08221887]])

In [138]:
arr2 = np.random.randn(5,3) # 연산 실습할 array 추가

In [139]:
arr2

array([[ 0.0946244 ,  1.16208117,  1.20608946],
       [ 0.58531508,  0.50858887, -0.43205584],
       [-0.76477164,  0.44291738,  1.33443735],
       [ 0.90293266, -0.63726212,  1.76818016],
       [ 0.8080801 , -2.3970795 ,  1.29571578]])

In [140]:
np.multiply(arr1,arr2)

array([[-0.08839643, -0.3897334 ,  0.60098414],
       [-0.07238587,  0.17647136, -0.26435608],
       [-0.11519342, -0.53719448, -1.07630127],
       [ 0.55440838,  0.44644708, -0.07464531],
       [-1.56557302, -0.05294148,  0.10653229]])

In [141]:
np.maximum(arr1,arr2)

array([[ 0.0946244 ,  1.16208117,  1.20608946],
       [ 0.58531508,  0.50858887,  0.61185628],
       [ 0.1506246 ,  0.44291738,  1.33443735],
       [ 0.90293266, -0.63726212,  1.76818016],
       [ 0.8080801 ,  0.02208582,  1.29571578]])

### 통계 Func

In [15]:
arr1

array([[-1.19221103, -0.78147096,  1.52427448],
       [ 0.68619103, -1.34498903, -0.55267736],
       [ 1.95189593, -0.22860076, -2.11950312],
       [ 1.3221908 , -0.12821303,  1.9311058 ],
       [ 0.03960364,  0.02657802,  0.03577257]])

In [143]:
np.sum(arr1)

-3.7667570894536735

In [145]:
np.sum(arr1,axis=1) # 1은 행별로 0은 열별로

array([-0.77126597,  0.8351687 , -1.86878832, -0.1287779 , -1.83309361])

In [146]:
np.sum(arr1,axis=0)

array([-2.23061718, -1.87973256,  0.34359266])

In [147]:
np.mean(arr1)

-0.25111713929691154

In [149]:
np.mean(arr1,axis=0) # 각열의 평균

array([-0.44612344, -0.37594651,  0.06871853])

In [150]:
np.std(arr1)

0.7105029861598278

In [151]:
np.min(arr1,axis=1) # 각행의 최소

array([-0.93418212, -0.12366992, -1.21285481, -0.70057056, -1.9373983 ])

In [16]:
np.argmin(arr1)

8

In [23]:
view= np.array([[  0,  1,  2],
                [  3,  4,  5],
                [  6,  7,  8],
                [  9, 10, 11],
                [ 12, 13, 14]])

In [24]:
np.argmax(arr1,axis=0)

array([2, 4, 3], dtype=int64)

In [154]:
np.cumsum(arr1)

array([-0.93418212, -1.26955748, -0.77126597, -0.8949359 , -0.54795355,
        0.06390273,  0.21452733, -0.99832748, -1.80488559, -1.19087703,
       -1.89144759, -1.93366348, -3.87106179, -3.84897596, -3.76675709])

In [155]:
np.cumsum(arr1,axis=1)

array([[-0.93418212, -1.26955748, -0.77126597],
       [-0.12366992,  0.22331242,  0.8351687 ],
       [ 0.1506246 , -1.06223021, -1.86878832],
       [ 0.61400856, -0.086562  , -0.1287779 ],
       [-1.9373983 , -1.91531248, -1.83309361]])

In [158]:
np.cumprod(arr1) # 누적곱

array([-9.34182119e-01,  3.13301670e-01,  1.56115562e-01, -1.93067996e-02,
       -6.69911863e-03, -4.09889780e-03, -6.17394858e-04,  7.48810325e-04,
       -6.03959039e-04, -3.70836019e-04,  2.59796796e-04, -1.09675544e-05,
        2.12485212e-05,  4.69291094e-07,  3.85845857e-08])

### np.where()

In [25]:
x = np.array([5,4,3,2,1,0])

In [27]:
np.where(x >=3) # 논리값으로 filter하듯 사용할 수 있다

(array([0, 1, 2], dtype=int64),)

In [28]:
np.where(x>=3, 3, x) # 3보다 크면 3, 아니면 x 

array([3, 3, 3, 2, 1, 0])

In [29]:
x  = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

In [30]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
idx, cols = np.where(x >= 6)

In [37]:
idx

array([1, 1, 1, 2, 2, 2, 2], dtype=int64)

In [33]:
cols

array([1, 2, 3, 0, 1, 2, 3], dtype=int64)

In [38]:
np.where(x >= 6) # 행,열 위치 (1,1) = 6, (1,2)=7 ...

(array([1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [39]:
list(zip(idx,cols))

[(1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3)]

### 기타 Func

In [5]:
arr1

array([[-1.19221103, -0.78147096,  1.52427448],
       [ 0.68619103, -1.34498903, -0.55267736],
       [ 1.95189593, -0.22860076, -2.11950312],
       [ 1.3221908 , -0.12821303,  1.9311058 ],
       [ 0.03960364,  0.02657802,  0.03577257]])

In [52]:
arr1 = np.array([[  2,  1,  0],
                [  3,  7,  5],
                [  6,  4,  8],
                [  9, 10, 11],
                [ 12, 13, 14]])

#### axis=1 행별로 오름차순

In [65]:
np.sort(arr1) #Default axis = 1 asc

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 4,  6,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [66]:
arr1

array([[ 2,  1,  0],
       [ 3,  7,  5],
       [ 6,  4,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [67]:
np.sort(arr1,axis=1)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 4,  6,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

#### axis=1 행별로 오름차순 정렬, [::-1,:] 행 내림차순

In [72]:
np.sort(arr1,axis=1)[::-1,:] 

array([[12, 13, 14],
       [ 9, 10, 11],
       [ 4,  6,  8],
       [ 3,  5,  7],
       [ 0,  1,  2]])

#### axis=1 행별로 오름차순 정렬, [:,::-1] 열 내림차순

In [73]:
np.sort(arr1,axis=1)[:,::-1] 

array([[ 2,  1,  0],
       [ 7,  5,  3],
       [ 8,  6,  4],
       [11, 10,  9],
       [14, 13, 12]])

In [69]:
arr1

array([[ 2,  1,  0],
       [ 3,  7,  5],
       [ 6,  4,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

#### axis=0 열별로 오름차순 정렬

In [68]:
np.sort(arr1,axis=0)


array([[ 2,  1,  0],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

#### axis=0 열별로 오름차순 정렬, [::-1,:] 행 내림차순

In [70]:
np.sort(arr1,axis=0)[::-1] 

array([[12, 13, 14],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 2,  1,  0]])

In [58]:
np.sort(arr1,axis=0)[::-1,]

array([[12, 13, 14],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 2,  1,  0]])

In [59]:
np.sort(arr1,axis=0)[::-1,:]

array([[12, 13, 14],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 2,  1,  0]])

#### axis=0 열별로 오름차순 정렬, [:,::-1] 열 내림차순

In [71]:
np.sort(arr1,axis=0)[:,::-1]

array([[ 0,  1,  2],
       [ 5,  4,  3],
       [ 8,  7,  6],
       [11, 10,  9],
       [14, 13, 12]])